update `requireFromGhost` in hopes of fixing bug
```
ERROR: Your storage adapter does not inherit from the Storage Base.
```

which is presumable caused by `requireFromGhost("./base", false)` returning null